### ISSUE TITLE
Tab Overflow buttons show up prematurely and flicker on and off

### ISSUE THREAD

**Issue by moonwalkersyrius** [black7375/Firefox-UI-Fix#403] opened 2022-06-02 04:45 UTC
With Lepton applied the Tab Overflow buttons (two scroll buttons - one on the left of the tab bar, one on the right - and the All Tabs button) show up inconsistently.

The easiest way to reproduce is to:
* open just enough new tabs to fill the full window width - Tab Overflow shows up. Expected: Tab Overflow remains hidden, as there is still plenty space for tabs to shrink, the way it stays hidden in a brand new clean FF profile.
* switch from the last, rightmost tab to some tab to the left of it. Any tab to the left will work - Tab Overflow gets hidden. Expected: Tab Overflow was hidden in the first place, as in brand new clean FF profile.
* keep opening new tabs until minimal tab width is reached - Tab Overflow remains shown, at this point as expected, regardless of which tab is selected, just like in a brand new clean FF profile.
* now start closing tabs slowly one by one - Tab Overflow is shown inconsistently, sometimes staying hidden, sometimes showing up, sometimes getting into a very annoying on-and-off flickering, unless the selected tab is not the rightmost. Expected: Tab Overflow remains hidden as soon as tab width grows beyond minimum, regardless which tab is active.

I've attempted to add the following CSS to force hide Tab Overflow, but it only changes the minimum tab width and does nothing to prevent Tab Overflow from showing up when it shouldn't:
```
.tabbrowser-tab {
	min-width: 10 !important;
}
.tab-content {
	overflow: hidden !important;
}
```

Environment:
Firefox 100.0.2 amd64 on Debian Sid, KDE Plasma with Breeze Dark theme running in X11 session.
Firefox 91.10.0esr amd64 on Ubuntu 20.04, KDE Plasma with Breeze Dark theme running in X11 session.

**Comment by BPower0036** [comment] 2022-06-04 09:06
I had the same problem. Thought that I did something wrong myself. Glad to see I'm not the only one.

**Comment by black7375** [comment] 2022-06-06 13:49
I also experienced this bug, but it disappeared as I updated Firefox to 102.

**Comment by BPower0036** [comment] 2022-06-15 09:44
I tested it with a new browser profile on Firefox 101.0.1 and there was no problem.
So I disabled certain files of of userChrome and I traced it down to the `tabbar/selected_tab/_bottom_rounded_corner.scss` file
If you disable https://github.com/black7375/Firefox-UI-Fix/blob/87334f4d890fbcf927e8435cb36f73e697d26a3b/src/tabbar/selected_tab/_bottom_rounded_corner.scss#L13 there is no problem anymore. When you enable it the problem is there again. (However by disabling you don't have a bottom rounded corner)

**Comment by moonwalkersyrius** [comment] 2022-06-16 15:09
The absence of a rounded corner at the bottom doesn't bother me in the slightest, so this is an acceptable to me solution.

**Comment by BPower0036** [comment] 2022-06-17 05:36
To be even more specific: the problem lays in the right bottom corner of the last tab if selected
If you remove the mentioned line and add the following there is also no problem, except the last tab not having a right bottom border
```
tab > stack::before,
tab:not([last-visible-tab="true"][visuallyselected]:not([first-visible-tab="true"])) > stack::after {
  position: absolute !important;
}
```

**Comment by black7375** [comment] 2022-07-29 01:57
Does current firefox(maybe `v103`) still have the same problem?

**Comment by moonwalkersyrius** [comment] 2022-07-29 02:48
103 is doing fine, ESR 102 as well.

**Comment by moonwalkersyrius** [comment] 2022-12-27 22:08
FF 108.0 with https://github.com/black7375/Firefox-UI-Fix/releases/tag/v6.5.2 again starts to flicker within certain range of number of tabs (not sure of the exact numbers, but tabs get small enough for the favicon to get clipped). Also, selecting the rightmost tab causes scroll buttons to show up when they are hidden otherwise.

**Comment by BPower0036** [comment] 2022-12-28 09:51
The same with me.

**Comment by black7375** [comment] 2023-06-18 06:01
Hello, the method applied in #643 seems to be effective here.
Can you test it?

**Comment by black7375** [comment] 2023-06-19 12:54
A similar issue has been resolved, so I'am closing this one as well.
If you have a problem, please comment.

**Closed by black7375** 2023-06-19 12:54 UTC
Labels: Issue::Bug, Env::Linux, Class::Bottom-Rounded-Corner, Component::Tabbar, Difficult::Unknown, Class::SideEffect, upstream
