### ISSUE TITLE
Photon - missing active tab highlight

### ISSUE THREAD

**Issue by evinnichenko** [black7375/Firefox-UI-Fix#848] opened 2023-12-20 19:48 UTC
### Describe the bug

Selected tab is not highlighted with brighter background (e.g. with light grey on light theme)

### Expected behavior

Selected tab stands out with different color
![image](https://github.com/black7375/Firefox-UI-Fix/assets/77905640/f87ba008-b2f7-4de5-8f46-4e2279c84954)
(part of a screenshot from Lepton's page, default Photon style, dark theme)

### Screenshots

![image](https://github.com/black7375/Firefox-UI-Fix/assets/77905640/2fc378bc-ae49-42a7-b327-245a825a4563)

### OS

Windows 10

### Firefox Version

121

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [X] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

Default settings

**Comment by Ziedge** [comment] 2023-12-20 20:47
I can confirm the bug since it's happening on my computer too
![image](https://github.com/black7375/Firefox-UI-Fix/assets/82708448/5fd78deb-68ff-4d13-a9c9-cf6afd701d17)

**Comment by russellweed** [comment] 2023-12-20 23:07
I can confirm this as well. It started happening today

Original Lepton
Leptop version: Latest as of 2023-12-20
Firefox version 121.0
Windows 11 Pro 23H3

![image](https://github.com/black7375/Firefox-UI-Fix/assets/1160446/eca1a370-059f-4da0-a087-e8f0e0c4ebf8)

**Comment by black7375** [comment] 2023-12-21 00:36
@Ziedge @russellweed This issue can be related #827 #828

**Comment by Farmbuyer** [comment] 2023-12-21 01:59
Yep, 8.50 under FF120.0.something was fine, upgrade to FF121.0 loses the tab highlight.  It's still present in private windows, however.

**Comment by mikesafari** [comment] 2023-12-21 19:00
> @Ziedge @russellweed This issue can be related #827 #828

Certainly looks like it. Is there a workaround until a fix is published?

**Comment by Farmbuyer** [comment] 2023-12-24 15:57
> > @Ziedge @russellweed This issue can be related #827 #828
> 
> Certainly looks like it. Is there a workaround until a fix is published?

From the comments in #827 the fix may already be published in the sense that FF 121.something will behave correctly again (unless I've misinterpreted the comment thread).  In the meantime, going to `about:config`, finding `userChrome.tab.photon_like_contextline` in the search box, and toggling to true will get **an** active tab highlight (although it's not the one we'd get from FF120).

It's possible to make the same change stick by going to the profile folder\* and editing `user.js`; the same setting is around line number 47 if it's an unmodified user.js from Lepton 8.5.0.  Obviously this file will be replaced when a new version of Lepton is dropped in, so there's no worry about having to undo the change manually.

\* `about:support`, find the profile folder entry, click open folder

**Comment by black7375** [comment] 2024-01-06 16:19
Hello, I believe the issue is resolved in v8.5.1.

**Comment by Ziedge** [comment] 2024-01-06 16:23
> Hello, I believe the issue is resolved in v8.5.1.

It is indeed !
Thanks again for everything !

**Comment by black7375** [comment] 2024-01-06 16:26
I've been a little busy with work lately, so I've been a little behind.
Instead, in the next release, I'll share an article I wrote over Christmas!!

**Closed by black7375** 2024-01-06 16:26 UTC
Labels: Issue::Bug, Env::Windows, Class::Color, Component::Tabbar, Distribution::Photon-Style, Browser::Upstream

**Comment by mikesafari** [comment] 2024-01-06 17:50
> Hello, I believe the issue is resolved in v8.5.1.

Doesn't seem to be for me... 🤔

I used the PowerShell installation (as normal) and an update finds nothing new and re-doing either Photon or Proton style still seems to result in an incorrect highlight.

**Comment by russellweed** [comment] 2024-01-07 02:24
@mikesafari 

It did work for me. The trick was to completely remove the old copy of Photon first. Nuke your userChrome, icons folder, and the user.js. Also, I did a manual install and did not use the PowerShell script (no idea if that has anything to do with it).

**Comment by mikesafari** [comment] 2024-01-12 23:05
> @mikesafari
> 
> It did work for me. The trick was to completely remove the old copy of Photon first. Nuke your userChrome, icons folder, and the user.js. Also, I did a manual install and did not use the PowerShell script (no idea if that has anything to do with it).

I guess I should clarify that I normally use the Proton-style branch. For now I've switched back to the main branch because it works but the Proton-style one is still broken.

Not a huge deal tbh, but would be nice to get the updates into that branch as well.

**Comment by Farmbuyer** [comment] 2024-01-14 19:03
Manually removing previous Lepton installation before updating to 121+8.5.1 fixed it here as well.

Cheers!
