### ISSUE TITLE
Selected address bar highlight incorrect

### ISSUE THREAD

**Issue by Tech-How** [black7375/Firefox-UI-Fix#849] opened 2023-12-20 20:12 UTC
### Describe the bug

When using the system default theme, the color of the selected suggestion in the address bar is purple, the color for the Firefox default dark theme, when it should be just a dimmer contrast. (The tab highlight color is also missing, but people have already reported that.)

### Expected behavior

The color of the selected suggestion should be the same as it was in the system default theme prior to Firefox 121.0.

### Screenshots

Before:
![image](https://github.com/black7375/Firefox-UI-Fix/assets/76794507/f8091aa3-c254-490f-8cf9-92181790dcf9)

After:
![image](https://github.com/black7375/Firefox-UI-Fix/assets/76794507/6f5ffd14-f902-48dc-bcf3-9b8d2f47d051)

### OS

Windows 10

### Firefox Version

v121.0

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by Farmbuyer** [comment] 2023-12-24 15:45
This looks like a possible duplicate of #848

**Comment by black7375** [comment] 2024-01-06 16:21
Let's I think it's the same problem as #848

**Closed by black7375** 2024-01-06 16:21 UTC
Labels: Issue::Bug, Issue::Duplicate, Env::Windows, Class::Color, Component::Tabbar, Distribution::Photon-Style, Browser::Upstream

**Comment by Tech-How** [comment] 2025-03-30 00:36
I just wanted to check in on this as I feel it was misinterpreted the first time. When I posted this I wasn't referring to the tab glitch that was happening at the time, but instead the purple-ish color that should just be an alpha channel layer on the selected omnibox suggestion. I can't re-open this myself.

![Image](https://github.com/user-attachments/assets/bf6c6da2-4162-4f8b-9677-91687c487af6)
