### ISSUE TITLE
Show more Bookmarks button

### ISSUE THREAD

**Issue by Kjaeremandag** [black7375/Firefox-UI-Fix#1015] opened 2024-11-04 20:23 UTC
### Describe the bug

Everytime i go on fullscreen on a video that button appears, if a shrink firefox and go full again, it disappears

It does not happen on original firefox UI

![Screenshot 2024-11-04 211938](https://github.com/user-attachments/assets/255e1e2f-bb76-4140-8271-eee95a0eede7)

### OS

Windows 11

### Firefox Version

132.0.1 

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [X] Dark
- [ ] Alpenglow (System: Light)
- [x] Alpenglow (System: Dark)
- [x] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by Aleksandra0056** [comment] 2024-11-06 10:41
I believe, that this is a duplicate of [Issue 685](https://github.com/black7375/Firefox-UI-Fix/issues/685).

**Comment by Kjaeremandag** [comment] 2024-11-08 13:20
> I believe, that this is a duplicate of [Issue 685](https://github.com/black7375/Firefox-UI-Fix/issues/685).

Then there is no fix for this?

**Comment by Aleksandra0056** [comment] 2024-11-08 13:25
> > I believe, that this is a duplicate of [Issue 685](https://github.com/black7375/Firefox-UI-Fix/issues/685).
> 
> Then there is no fix for this?

I apologise if you misunderstood. With the term "I believe that this is a duplicate of Issue 685" I meant, that the issue ticket you published is already documented. There indeed would be an eventual fix in future, but since this same issue is documented in Issue ticket number 685, it means, that it's a duplicate of it. Duplicate issues usually become closed as not planned because developers don't want their issue trackers cluttered since they are already documented.

If you think, that it's unfair, then I can add a "see also" comment with reference to your issue. But remember, that issue reporting isn't a competetion.

**Comment by black7375** [comment] 2024-11-14 06:52
When I tested it again this time, it was reproducible.
I'll handle it all at once in #685
Thank you for the report.

**Closed by black7375** 2024-11-14 06:52 UTC
Labels: Issue::Bug, Issue::Duplicate
