### ISSUE TITLE
Image next to firefox sync information seems to be broken

### ISSUE THREAD

**Issue by Jhyub** [black7375/Firefox-UI-Fix#14] opened 2021-05-31 04:12 UTC
**Describe the bug**
Image next to firefox sync information in the hamburger menu seems to be broken when firefox sync is active.
Happens on both lepton and photon, didn't test other branches yet

**Expected behavior**
The mozilla account avatar displayed

**Screenshots**
| **Before (Clean environment)** | **After photon**  |
| --- | --- |
| ![original](https://user-images.githubusercontent.com/33977729/120137493-6897aa00-c20f-11eb-9f82-501fc7a05629.png) | ![photon-style](https://user-images.githubusercontent.com/33977729/120137506-70574e80-c20f-11eb-8b93-e372b9f9ed50.png) |

**Environment (please complete the following information):**
 - Firefox Version: 89.0b15
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Comment by black7375** [comment] 2021-05-31 06:44
Need more information.

Please let us know the results after doing the following:

1. Run Browser Tool Box

https://www.reddit.com/r/FirefoxCSS/comments/73dvty/tutorial_how_to_create_and_livedebug_userchromecss/

> ### Pre-setup
>  -  Press Ctrl + Shift + I on Win/Linux or Cmd + Opt + I on Mac
>  -  Click on the cog that appears in a right or left top corner, next to other buttons.
>  - Scroll down to Advanced Settings and check the settings "Enable browser chrome and add-on debugging toolboxes" and "Enable remote debugging".
>  - Close the developer tools panel and proceed with next tutorial

> ### Testing a style
> - Press Ctrl + Alt + Shift + I on Win/Linux or Cmd + Opt + Shift + I on Mac
> - A permission dialog will prompt you to allow remote debug, accept

2. Search `--avatar-image-url`
![Browser Tool Box](https://user-images.githubusercontent.com/25581533/120150110-2a33c800-c1da-11eb-9c06-f9007b8f3130.png)

Does the displayed image URL appear accessible and normal?

**Comment by Jhyub** [comment] 2021-05-31 07:02
![image](https://user-images.githubusercontent.com/33977729/120153267-79551980-c229-11eb-829b-9afdfb0a67eb.png)
Points to the correct image.
[https://firefoxusercontent.com/e54247b41abfc3f7c45bbae261adebc4](https://firefoxusercontent.com/e54247b41abfc3f7c45bbae261adebc4)

**Comment by black7375** [comment] 2021-05-31 07:09
Ok, It's reproducible.
I'll fix it.

**Comment by black7375** [comment] 2021-05-31 07:29
Now it works fine on my computer.
Try it.

**Comment by Jhyub** [comment] 2021-05-31 07:40
works great, thanks!

**Comment by black7375** [comment] 2021-05-31 07:40
yeah. nice report

**Comment by Bad3r** [comment] 2021-05-31 12:21
Is it possible to make the image circular?

**Comment by black7375** [comment] 2021-05-31 12:32
@Bad3r 
Maybe it's possible with `border-radious`.
Since the image shown in the Account Panel is circular, I think it is better to match it.

I'll work on it tomorrow.

**Comment by Bad3r** [comment] 2021-05-31 12:45
> @Bad3r 
> 
> Maybe it's possible with `border-radious`.
> 
> Since the image shown in the Account Panel is circular, I think it is better to match it.
> 
> 
> 
> I'll work on it tomorrow.

Thanks! That would be great. I think it would look much better than the square image

**Comment by 7k5x** [comment] 2021-06-01 00:12
Is it possible to implement toggling of icons such as icons on/off?

**Comment by black7375** [comment] 2021-06-01 01:38
> Is it possible to implement toggling of icons such as icons on/off?

Adding dynamic features is not possible with CSS.

It is possible using JS, but it is difficult to set up, so we have not yet officially considered introducing it.
Developers will have no problems, but regular users may experience difficulties.

**Comment by black7375** [comment] 2021-06-01 01:49
@Bad3r 

I like it. good.
![account circle](https://user-images.githubusercontent.com/25581533/120255358-49cefd00-c27b-11eb-9f78-02415df8ca8f.png)

**Comment by Bad3r** [comment] 2021-06-01 01:50
Looks great! going to test it

**Comment by Qwerty-Space** [comment] 2021-06-04 18:09
I'm having a similar issue.  The avatar image and plenty of other icons aren't showing up.  I'm running the photon-like-panel branch on Linux.


![image](https://user-images.githubusercontent.com/6967592/120839856-5a27f600-c561-11eb-9f10-f5a57608c19d.png)
![image](https://user-images.githubusercontent.com/6967592/120845136-4cc23a00-c568-11eb-8b6c-a9a4795b3304.png)

https://firefoxusercontent.com/c43aaa6bbd2fa494c8a5cb5fa921f5aa

**Comment by black7375** [comment] 2021-06-05 04:07
I checked. It should be fixed by the end of the week.

**Comment by black7375** [comment] 2021-06-05 14:12
@Qwerty-Space  Would you like to try it?

**Comment by Qwerty-Space** [comment] 2021-06-05 14:21
> @Qwerty-Space Would you like to try it?

Sure, but are those changes for the photon-like-panel branch?  I don't need all of the other changes because I don't have a tab bar

**Comment by black7375** [comment] 2021-06-05 14:24
Yes, originals do not need to be set because they have all icons.
As I tested, the spacing of align in the subpanel should be hardcoded to `8px`.

**Comment by Qwerty-Space** [comment] 2021-06-05 14:35
@black7375 it doesn't look like you've pushed the changes to this branch
![image](https://user-images.githubusercontent.com/6967592/120895148-92880c80-c613-11eb-9d8c-5fbf55603237.png)

**Comment by black7375** [comment] 2021-06-05 14:37
Ah...I updated directly to `photon-style`.
I will cherry-pick.

**Comment by black7375** [comment] 2021-06-05 14:45
apply now

**Comment by black7375** [comment] 2021-06-05 14:56
FYI, the panel width has increased width to truncation issues in some languages. #40

**Comment by Qwerty-Space** [comment] 2021-06-05 15:02
> apply now

Still having the same issues

**Comment by black7375** [comment] 2021-06-05 15:09
Are you run `Click the Clear startup cache...` at `about:support`?

**Comment by Qwerty-Space** [comment] 2021-06-05 15:16
> Are you run `Click the Clear startup cache...` at `about:support`?

Tried that.  Still didn't work.

**Comment by black7375** [comment] 2021-06-05 15:20
That's weird. Have you been updated to the latest commit?
On my computers, the bug is gone and is no longer reproducible.

**Comment by Qwerty-Space** [comment] 2021-06-05 15:40
> That's weird. Have you been updated to the latest commit?
> On my computers, the bug is gone and is no longer reproducible.

Yup

**Comment by Qwerty-Space** [comment] 2021-06-05 16:15
I've got it working differently now.  I cloned the master branch and added this to my userChrome.css

```css
/* Reduce padding, and re-arrange content in the hamburger menu */
@import "Firefox-UI-Fix/userChrome.css";
```

**Comment by black7375** [comment] 2021-06-05 16:19
`master` has all the icons so the behavior is different.
Use [`photon-style`](
https://github.com/black7375/Firefox-UI-Fix/tree/photon-style) if you hate all icons.

**Closed** 2021-06-05 18:14 UTC
Labels: Class::Icon, Compenent::Panel, Difficult::Easy, Env::Linux, Priority::High, bug, help wanted

**Comment by black7375** [comment] 2021-06-05 18:15
A related issue already exists and should be discussed here. #41
