### ISSUE TITLE
Text overlap when auto hiding navbar

### ISSUE THREAD

**Issue by Zabooby** [black7375/Firefox-UI-Fix#517] opened 2022-11-27 18:47 UTC
The text of bookmarks overlaps the url bar text. 

![image](https://user-images.githubusercontent.com/78969986/204153904-369b9fca-fefb-4560-ae3f-db1ca4ceb563.png)

**Comment by black7375** [comment] 2022-11-30 15:49
Please write down your environment and settings.
Without it, the reproduction is very hard.

**Comment by black7375** [comment] 2022-12-05 18:30
Hmm..There seems to be more conditions.
In my environment, urlbar background does not seem transparent.

![image](https://user-images.githubusercontent.com/25581533/205713858-4bfbcfe6-1e16-4dea-a243-5a755128452b.png)

**Comment by Zabooby** [comment] 2022-12-05 21:17
Maybe it's because my url background colour and bookmarks bar colour are the same?

Also it only overlaps with icons/text on the bookmarks bar

![image](https://user-images.githubusercontent.com/78969986/205744484-5e464adf-c359-48e1-8df5-3e23eea9aa93.png)

**Comment by black7375** [comment] 2022-12-05 21:25
As far as I know, it was fixed in [`v6.4.0`](https://github.com/black7375/Firefox-UI-Fix/releases/tag/v6.4.0).

See #501 (https://github.com/black7375/Firefox-UI-Fix/commit/aff13a5984c53aca5a3282a34dacb64e5014c0c7), https://github.com/black7375/Firefox-UI-Fix/commit/1cbcb9a9f16fdf5b548000ad35fa198b587c7cfb

**Comment by Zabooby** [comment] 2022-12-06 18:14
I've made my own solution, put everything in folders so there is no overlap. Should I close the issue?
![image](https://user-images.githubusercontent.com/78969986/205989476-f2ed695d-8527-4f76-887e-a725c5f4d437.png)

**Comment by black7375** [comment] 2022-12-06 18:17
Once it can't reproduced, I will close it if it has been solved.
If you have the same problem in the latest version later, please contact me again. :+1:

**Closed by black7375** 2022-12-06 18:17 UTC
Labels: Issue::Bug, Env::Windows, Class::Color, Difficult::Unknown, Component::URLbar

**Comment by Zabooby** [comment] 2022-12-06 20:04
I'm already on the latest version. Also is it possible to change the colour of the separator in the search bar in the picture above?
![image](https://user-images.githubusercontent.com/78969986/206011082-acbc88ff-2874-4ae5-8a81-f49f5c467efd.png)

**Comment by black7375** [comment] 2022-12-06 20:57
It's strange..

If you solve it, please share the relevant code here.
It helps other users who patch or search.

---

Here is a urlView separator color
```css
.urlbarView-title-separator::before {
  color: red;
}
```

**Comment by Zabooby** [comment] 2022-12-06 21:21
I'll try and set up a fresh profile myself tomorrow and see if can reproduce it, I might have forgot some changes I made. I'll keep you posted.

I tried the code but the colour isn't changing.

**Comment by Zabooby** [comment] 2022-12-07 13:10
> It's strange..
> 
> If you solve it, please share the relevant code here. It helps other users who patch or search.
> 
> Here is a urlView separator color
> 
> ```css
> .urlbarView-title-separator::before {
>   color: red;
> }
> ```

I just made a fresh profile and installed v6.5.1 the bug is still there. These are all the changes that I had, see if you can replicate:

### User.js
```
user_pref("userChrome.icon.disabled",                       true);
user_pref("userChrome.tab.dynamic_separator",          false); // Original, Proton
user_pref("userChrome.autohide.navbar",                     true);
user_pref("userChrome.autohide.toolbar_overlap",            true);
```

## userChrome.css
```
html#main-window menupopup:not(.in-menulist) {
  --menu-border-color: black !important;
  --panel-border-color: var(--menu-border-color) !important;
}
html#main-window menupopup:not(.in-menulist) menuseparator {
 --menu-border-color: black !important;
 border-top: 1px solid var(--menu-border-color) !important;
}
#customization-container {
	background-color: #1E2021 !important;
	background-image: none !important;
}

#customization-footer {
	border: black !important;
	background-color: #1E2021 !important;
}
:root {
  --panel-separator-color: black !important;
}

html#main-window menupopup:not(.in-menulist, [placespopup]) menuseparator,
toolbarbutton menupopup[placespopup] menuseparator::before {
  --menu-border-color: black !important;
}
```
```
.urlbarView-title-separator::before {
  color: black;
}
```

Also the separator that I was talking about above was this one, is it possible to change the colour?:
![image](https://user-images.githubusercontent.com/78969986/206187584-5008fd57-3d1e-459e-b7da-da6d9a055dab.png)
