### ISSUE TITLE
Style ignored if window width is larger than 2500 px.

### ISSUE THREAD

**Issue by th-joerger** [black7375/Firefox-UI-Fix#170] opened 2021-08-16 08:47 UTC
**Describe the bug**
White on white style starting on the left, when window width is larger than 2500 px.

**Expected behavior**
Window width should not matter.

**Screenshots**

![whiteborder](https://user-images.githubusercontent.com/30830429/129536744-3cffe495-8131-449c-8afb-c9749c244470.png)

**Environment (please complete the following information):**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version:  	91.0
 - OS:
   - [ ] Linux
   - [x] Windows 10
   - [ ] Mac
   - [ ] Others: 

 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Comment by black7375** [comment] 2021-08-16 11:52
This is because if there is an image, it will not be filled.
Same problem with pure proton.
![image](https://user-images.githubusercontent.com/25581533/129556070-60e363a4-45ab-462e-b404-2545b9df6018.png)

Now it will be solved.
It's only added to `Original Lepton` at the moment and will be fixed in photon-style soon.
![image](https://user-images.githubusercontent.com/25581533/129556959-6ad7094f-9d39-4b49-9dec-a13842e7d7a8.png)

**Closed by black7375** 2021-08-16 11:52 UTC
Labels: Issue::Bug, Priority::High, Component::Toolbar, Class::Size, Photon-Style

**Comment by th-joerger** [comment] 2021-08-16 12:17
Thanks for the quick fix. But I would recommend to use backgound-size: contain, as background-size: cover stretches the image to bits.

**Comment by black7375** [comment] 2021-08-16 12:21
I used a `cover` because there might be some images that don't match the proportions.
Wouldn't it be better to keep the percentage chosen by the theme creators?

**Comment by th-joerger** [comment] 2021-08-16 12:36
With my current theme ([Abstract splash](https://addons.mozilla.org/de/firefox/addon/abstract-splash/)) it gets blurry and not usable. I actually solved it now by manually extending the header image with more black pixels and signing a new custom theme over the Mozilla themes homepage.

**Comment by black7375** [comment] 2021-08-16 12:40
Oh confirmed.
I'll change it.

**Comment by hdk5** [comment] 2021-08-16 20:25
Changes made by this issue break my theme.

Original (without Lepton or with `background-size` rule removed):
![2021-08-16 23_09_41-Window](https://user-images.githubusercontent.com/2550010/129624913-5655ed63-5aab-40f7-8ede-05a3e8138e7a.png)
`background-size : cover;`:
![2021-08-16 23_15_11-Window](https://user-images.githubusercontent.com/2550010/129624975-0e2ea1fa-e962-4500-aa27-fd6baf786501.png)
`background-size : contain;`:
![2021-08-16 23_11_01-Window](https://user-images.githubusercontent.com/2550010/129625076-f0c76336-e1ae-49d5-8545-c8fc348519c2.png)

**Comment by black7375** [comment] 2021-08-17 00:22
Then, I will use a media query to apply it only when it is larger than 2500px.

**Comment by th-joerger** [comment] 2021-08-17 07:49
The 2500 px was the maximum size of the header image in my theme. This might not be a universal constant though.

**Comment by hdk5** [comment] 2021-08-17 08:33
I think, the issue with OP's theme is not `background-size`, but `background-color`, i.e. background color defined by Lepton in userChrome.css takes precedence over background color defined by theme.
![2021-08-17 11_17_14-Window](https://user-images.githubusercontent.com/2550010/129692298-7565ff85-a9c1-401b-9138-063d572b4e0c.png)
![2021-08-17 11_17_46-Window](https://user-images.githubusercontent.com/2550010/129692316-39345e03-46f3-4d47-ac20-aabf9b78ce4b.png)

**Comment by th-joerger** [comment] 2021-08-17 10:11
I think you are absolutely right!

**Comment by th-joerger** [comment] 2021-08-17 16:25
Also, ignoring the themes color scheme has more side effects. I just found out, that after proper restart of FF, the color is white on white in the context menu.

![white_context_menu](https://user-images.githubusercontent.com/30830429/129763975-e330451f-dd27-48b3-8bc8-c3cad1feb362.png)

**Comment by black7375** [comment] 2021-08-17 16:41
I'm busy today. I'll check one by one tomorrow.

**Comment by black7375** [comment] 2021-08-18 11:58
The reason this code is included is for theme compatibility.
https://github.com/black7375/Firefox-UI-Fix/blob/319c39dbd07da2ed763a44928803b3f66ffe018c/userChrome.css#L25-L42

**Before**
![image](https://user-images.githubusercontent.com/25581533/129859040-539ad480-9ce9-4950-94f8-fadbba91f320.png)
**After**
![image](https://user-images.githubusercontent.com/25581533/129856345-761c3aa6-c600-4a22-816d-4cb54b10b840.png)

By default, the header image appears normally in Win7, but is truncated in other OSs (Win10, Linux, Mac).

---
A lot of themes seem to have a horizontal size of `2500px`.
- https://addons.mozilla.org/en-US/firefox/addon/dark-blue/
![image](https://user-images.githubusercontent.com/25581533/129893812-4880074e-07a4-49c1-8d5d-48f7f7f44bec.png)
- https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/
![image](https://user-images.githubusercontent.com/25581533/129893871-babbbc13-1a3e-47f6-b7a7-a83be99d47ce.png)

In the pure theme, truncation occurs, so I think it is better to have the following code even if there is some distortion in terms of defending the worst case.
https://github.com/black7375/Firefox-UI-Fix/blob/c40b4e28fd97e233d75d633ed68a0667ede2da09/userChrome.css#L33-L37

**Comment by th-joerger** [comment] 2021-08-18 21:36
> Are you using the latest commit?
> I found the case in #157 and modified it.

Apparently, I was on the old version. It is fixed in the new version. Thanks!

> In the pure theme, truncation occurs, so I think it is better to have the following code even if there is some distortion in terms of defending the worst case.

It is fine for me, as I solved it with my own theme. I still don't understand, why it can't be handled like in FF vanilla?

**Comment by black7375** [comment] 2021-08-19 05:57
> A lot of themes seem to have a horizontal size of `2500px`.
> - https://addons.mozilla.org/en-US/firefox/addon/dark-blue/
> ![image](https://user-images.githubusercontent.com/25581533/129893812-4880074e-07a4-49c1-8d5d-48f7f7f44bec.png)
> - https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/
> ![image](https://user-images.githubusercontent.com/25581533/129893871-babbbc13-1a3e-47f6-b7a7-a83be99d47ce.png)

These are what you see in FF vanilla.
This patch makes up for the shortcomings.

**Comment by th-joerger** [comment] 2021-08-19 06:41
> These are what you see in FF vanilla.
> This patch makes up for the shortcomings.

I see, so it is more of a Firefox prolem, less of a Firefox-UI-Fix-problem. Thanks a lot!

**Comment by Poopooracoocoo** [comment] 2021-08-19 11:16
@th-joerger if you post a bugzilla report i'll vote for it
